# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}@args:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel" # for virtualization
    "i2c-dev" # for exploiting the DDC (Display Data Channel)
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/EFI";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/LinuxRoot";
    fsType = "ext4";
  };

  fileSystems."/media/${args.vars.mainUsername}/Data" = {
    device = "/dev/disk/by-label/Data";
    fsType = "ext4";
    options = [
      "user"
      "defaults"
      "X-mount.owner=${args.vars.mainUsername}"
      "X-mount.group=users"
    ];
  };

  fileSystems."/mnt/my-ramdisk" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "user"
      "defaults"
      "X-mount.owner=${args.vars.mainUsername}"
      "X-mount.group=users"
      "size=100M"
    ];
  };

  # Disable swap
  boot.kernel.sysctl = {
    "vm.swappiness" = 0;
  };
  swapDevices = [ ];

  # Don't bloat disk with tmp files
  boot.tmp.cleanOnBoot = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp57s0u1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault args.vars.system;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Configure printers
  hardware.printers = {
    ensureDefaultPrinter = "XEROX_B215";
    ensurePrinters = [
      {
        name = "XEROX_B215";
        deviceUri = "socket://192.168.1.2";
        model = "drv:///sample.drv/generic.ppd";
        description = "Xerox B215 Multifunctional Printer";
        location = "Living Room";
        ppdOptions = {
          PageSize = "A4";
          InputSlot = "Default";
          Duplex = "DuplexNoTumble";
          Option1 = "True";
        };
      }
    ];
  };

  # NOTE: Temporary solution for my LG27GS95QE OLED monitor
  # fonts.fontconfig.antialias = false;
  # fonts.fontconfig.subpixel.rgba = "rgb";
  fonts.fontconfig.subpixel.lcdfilter = "light";

  # Automatically sets up secure udev rules and creates the 'i2c' group
  # For communication with monitors via ddcutil
  hardware.i2c.enable = true;
  
  services.udev.extraRules = ''
    # Keychron hidraw (Needed for WebUSB access on Chromium browsers)
    KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="3434", TAG+="uaccess"

    # Configure USB
    SUBSYSTEM=="usb",  ATTRS{idVendor}=="3434", ATTRS{idProduct}=="0a38", TAG+="uaccess"

    # Configure 2.4GHz
    SUBSYSTEM=="usb",  ATTRS{idVendor}=="3434", ATTRS{idProduct}=="d030", TAG+="uaccess"
  '';
}
