theme = "onelight"

[editor]
shell = ["bash", "-c"]
auto-format = false
auto-save = true
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control", "spacer", "diagnostics"]
center = ["file-name", "file-modification-indicator"]
right = ["selections", "file-encoding", "file-line-ending", "position", "position-percentage", "spacer"]

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "→"
tabpad = "·"

[editor.indent-guides]
render = true

[editor.gutters]
layout = ["spacer", "diagnostics", "line-numbers", "spacer", "diff"]
