# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel" # for virtualization
    "i2c-dev" # for exploiting the DDC (Display Data Channel)
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/34f9932a-0ee9-467f-9191-815515e0cbfe";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B036-4B68";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };
  fileSystems."/media/matei/Date" = {
    device = "/dev/disk/by-label/Date";
    fsType = "ext4";
    options = [
      "user"
      "defaults"
      "X-mount.owner=matei"
      "X-mount.group=users"
    ];
  };

  # Disable swap
  boot.kernel.sysctl = {
    "vm.swappiness" = 0;
  };
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp57s0u1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Configure printers
  hardware.printers = {
    ensureDefaultPrinter = "XEROX_B215";
    ensurePrinters = [
      {
        name = "XEROX_B215";
        deviceUri = "socket://192.168.1.2";
        model = "drv:///sample.drv/generic.ppd";
        description = "Xerox B215 Multifunctional Printer";
        location = "Living Room";
        ppdOptions = {
          PageSize = "A4";
          InputSlot = "Default";
          Duplex = "DuplexNoTumble";
          Option1 = "True";
        };
      }
    ];
  };

  # For my LG27GS95QE OLED monitor
  # fonts.fontconfig.antialias = false;
  # fonts.fontconfig.subpixel.rgba = "rgb";
  fonts.fontconfig.subpixel.lcdfilter = "light";

  services.udev.extraRules = ''
    # Disable wakeup from sleep from USB interrupt
    ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x8086", ATTR{device}=="0x9d2f", ATTR{power/wakeup}="disabled"

    # I can't remember the purpose of this one
    KERNEL=="i2c-[0-9]*", GROUP:="users"

    # For my RTL-SDR TRNG project
    SUBSYSTEM=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838", MODE:="0666"

  '';
}
